-- Query to calculate Micro-Level Economics (Product Performance)
WITH RankedModels AS (
    SELECT
        Model_Name,
        SUM(grand_total) AS total_value,
        SUM(CASE WHEN is_duty_anomaly = 'Yes' THEN 1 ELSE 0 END) AS anomaly_count
    FROM trade_cleaned
    -- Filter out models that failed parsing or are generic
    WHERE Model_Name IS NOT NULL AND Model_Name != 'Other' AND Model_Name != ''
    GROUP BY Model_Name
)
SELECT
    t1.Model_Name,
    -- 1. Total value generated by the model
    t1.total_value,
    -- 2. Average landed cost across all shipments for this model
    ROUND(AVG(t2.landed_cost_per_unit), 2) AS average_landed_cost,
    -- 3. Count of shipments flagged as duty anomalies for this model
    t1.anomaly_count
FROM RankedModels t1
JOIN trade_cleaned t2 ON t1.Model_Name = t2.Model_Name
GROUP BY t1.Model_Name, t1.total_value, t1.anomaly_count
ORDER BY t1.total_value DESC;